### ISSUE TITLE
Unable to send forgot password email

### ISSUE THREAD

**Issue by bbtdigitalkaran** [lekoala/silverstripe-mandrill#27]
Unable to send the email with default SS forgot password form.
This is in the error logs
` PHP Fatal error: Cannot access self:: when no class scope is active in /silverstripe-mandrill-master/code/MandrillEmail.php on line 908`

**Comment by lekoala** [comment]
Seems like the url rewriter not working.. which php  version are you running? I never had this problem before

**Comment by bbtdigitalkaran** [comment]
I have a client who is using 5.3...pretty old to handle this?

**Comment by lekoala** [comment]
Yes maybe the class is not resolved within the closure. The code should be very easy to change to support 5.3. feel free to make the change.

**Comment by bbtdigitalkaran** [comment]
Yeah change that to public static function. Thanks
