### ISSUE TITLE
Emails not coming into model admin

### ISSUE THREAD

**Issue by intotheweb101** [lekoala/silverstripe-mandrill#36]
hello 

I have maindrill set up emails are being sent from the server, but it isn't being pulled into the Admin in the CMS.

Any advice on getting this working?

I am running Silverstripe 4

Thanks

**Comment by lekoala** [comment]
Well there is a cache so it might take some time to display. You can flush the cache using query string (I don't remember from the top of my head) or press the search button to see if it does anything. Maybe dump the result of the API call and see if you get anything there. Last time i've checked it was working fine

**Comment by lekoala** [comment]
@intotheweb101 fixed in latest release
