### ISSUE TITLE
SEND_ALL_EMAILS_TO not used

### ISSUE THREAD

**Issue by alex-dna** [lekoala/silverstripe-mandrill#39]
Hi.

Thanks for the module, it is very useful.

I'm having an issue with the SEND_ALL_EMAILS_TO though.
It seems like if I use MAILER_DSN=mandrill+https://KEY@default (or API) rather than SMTP, the process that would replace the To address from the environment vars doesn't kick in.

Is this expected?

If I var_dump the MailInterface in SilverStripe\Control\Email\Email::send, I get the Mandrill Transport Interface as expected, but the dispatcher is null. I believe the dispatcher should potentially be a Symfony\Component\EventDispatcher\EventDispatcher, like for the smtp mailer.

I don't know if I'm missing a config somewhere, but I can't find a clue in the docs.
Any idea what I might be missing here?

Thanks.

**Comment by lekoala** [comment]
hi @alex-dna 

wow, i'm not sure how i missed that...

can you try the latest updates on master? happy to tag a stable release if the changes i made work for you

i added a unit test for this case

**Comment by alex-dna** [comment]
Hi @lekoala , thanks for the speedy response and fix.
It seems to work indeed, with both the https and api method.
I'll keep an eye for the new tag, so I can update my app.
Thank you.
