### ISSUE TITLE
Add some version tags

### ISSUE THREAD

**Issue by camfindlay** [lekoala/silverstripe-mandrill#5]
Great module, if you are starting to add new things it might be good to start thinking about tagging stable versions rather than having everyone use dev-master :+1:

**Comment by lekoala** [comment]
The current master branch is quite WIP this is why I'm not tagging this as much as I should. But once the email templates functionality is finished I will do this :-)

**Comment by mediabeastnz** [comment]
Yeah keen for this :+1:

**Comment by camfindlay** [comment]
You can always tag as a 0.1.0 which indicates it's still in working... Doing this really helps others include the module in their composer :)

**Comment by camfindlay** [comment]
nice one on tagging up some versions :)
