### ISSUE TITLE
Sub accounts can see other sub accounts activity.

### ISSUE THREAD

**Issue by mediabeastnz** [lekoala/silverstripe-mandrill#9]
When using the sub accounts feature there is a bit of a privacy issue in the modal admin.
Any sub account can see the activity of another sub account using the same API key.

I have created a pull request to fix this issue by creating a new private mode but I thought I would still post here incase anyone else was wanting to use this module in this way.

**Comment by lekoala** [comment]
You are totally right. Actually, I've never used the subaccount functionnality myself. But it is a sane default to restrict the search to the defined subaccount. I've updated the master to reflect this.

**Comment by mediabeastnz** [comment]
Thanks heaps! Time to update a couple sites... :)
